# Generated by Django 3.0.2 on 2020-02-25 16:36

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalhosRealizados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalhosrealizados',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='trabalhosrealizados',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='trabalhos_realizados', verbose_name='Foto'),
        ),
    ]
