# Generated by Django 3.0.2 on 2020-02-25 14:24

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('habilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='habilidade', verbose_name='Foto'),
        ),
    ]
