# Generated by Django 3.0.2 on 2020-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experienciaProfissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissiona',
            name='empresa',
            field=models.CharField(max_length=100, verbose_name='Empresa'),
        ),
    ]
